Fixes on endpoint rules, firewall rules, and deployment.

diff --git a/containers/sapio_bls/Dockerfile b/containers/sapio_bls/Dockerfile
--- a/containers/sapio_bls/Dockerfile
+++ b/containers/sapio_bls/Dockerfile
@@ -8,12 +8,18 @@ RUN mkdir -p /opt/sapiosciences/velox_server/addons/
 
 COPY files/foundations.jar /opt/sapiosciences/velox_server/addons/foundations.jar
 COPY files/analytics.jar /opt/sapiosciences/velox_server/addons/analytics.jar
-#COPY customizations.jar /opt/sapiosciences/velox_server/addons/customizations.jar
+COPY customizations.jar /opt/sapiosciences/velox_server/addons/customizations.jar
 
 WORKDIR /opt/sapiosciences/velox_server/addons/
 RUN unzip -o analytics.jar "*lib/*" "plugins/*" "wars/*"
 RUN unzip -o foundations.jar "*lib/*" "plugins/*" "wars/*"
-#RUN unzip -o customizations.jar "*lib/*" "plugins/*" "wars/*"
+RUN if test -f customizations.jar; then  \
+    echo "customizations.jar found. Extracting...";  \
+    RUN unzip -o customizations.jar "*lib/*" "plugins/*" "wars/*"; \
+    echo "customizations.jar extracted successfully.";  \
+    else echo "customizations.jar not found";  \
+    exit 1;  \
+    fi
 
 RUN mv wars clientplugins;
 RUN mv applib sharedlib
